stack-set: assumable-roles
capabilities:
  - CAPABILITY_NAMED_IAM
main-account-parameter: true
all-subaccounts: true
max-concurrent-percentage: 100
regions:
  - us-east-1
region: us-east-1
tags:
  ValidateAllSubAccounts: true
  ValidateRegions: us-east-1
parameters:
  AllowedRegions: us-east-1
