stack-set: assumable-roles
capabilities:
  - CAPABILITY_NAMED_IAM
main-account-parameter: true
all-subaccounts: true
regions:
  - us-east-1
tags:
  ValidateAllSubAccounts: true
  ValidateRegions: us-east-1