Mappings:
  RegionMap:
    {% for Region in AWSRegions %}
    {{Region}}:
      Enabled: {% if Region in EnabledRegions %}true{%else%}false{%endif%}
    {% endfor %}

Conditions:
  IsEnabledRegion: !Equals [!FindInMap ['RegionMap', !Ref 'AWS::Region', 'Enabled'], 'true']
  IsDisabledRegion: !Equals [!FindInMap ['RegionMap', !Ref 'AWS::Region', 'Enabled'], 'false']

Resources:
  {% for Rule, Resource in EnabledConfigRules.items() %}
  {{Rule | resource}}:
    Condition: IsEnabledRegion
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: "{{Rule}}"
      Scope:
        ComplianceResourceTypes:
          {% if Resource is string %}
          - {{Resource}}
          {% else %}
          {{ Resource }}
          {% endif %}
      Source:
        Owner: AWS
        SourceIdentifier: "{{Rule}}"
  {% endfor %}

