# Resources:
#   RootAccountMFAEnabledConfigRule:
#     Condition: IsGlobalRegion
#     Type: AWS::Config::ConfigRule
#     Properties:
#       ConfigRuleName: "ROOT_ACCOUNT_MFA_ENABLED"
#       Source:
#         Owner: AWS
#         SourceIdentifier: "ROOT_ACCOUNT_MFA_ENABLED"
