stack: vpc
stack-set: vpc
vars:
  AvailabilityZones: 3
  GatewayEndpoints: []
  InterfaceEndpoints: []
#  AccountCIDR:
#    123456789:
#      "us-east-1": 11.0.0.0/16
parameters:
  PrivateNatGateway: none
all-subaccounts: true
max-concurrent-percentage: 100
tags:
  ValidateAllSubAccounts: 'true'
  ValidateRegions: us-east-1
capabilities:
  - CAPABILITY_IAM
main-account-parameter: true
region: us-east-1
