Transform: AccountIteration
Resources:
  AdminGroupACCOUNT_ID:
    Properties:
      GroupName: AdminGroupACCOUNT_ID
      Path: /admin/ACCOUNT_ID/
      Policies:
      - PolicyDocument:
          Statement:
            - Action:
                - sts:AssumeRole
              Effect: Allow
              Resource:
                - arn:aws:iam::ACCOUNT_ID:role/admin
                - arn:aws:iam::ACCOUNT_ID:role/user
        PolicyName: AdminPolicyACCOUNT_ID
    Type: AWS::IAM::Group
  UserGroupACCOUNT_ID:
    Properties:
      GroupName: UserGroupACCOUNT_ID
      Path: /user/ACCOUNT_ID/
      Policies:
      - PolicyDocument:
          Statement:
            - Action:
                - sts:AssumeRole
              Effect: Allow
              Resource: arn:aws:iam::ACCOUNT_ID:role/user
        PolicyName: UserPolicyACCOUNT_ID
    Type: AWS::IAM::Group
