Resources:
  AdminGroup:
    Properties:
      GroupName: AdminMasterAccount
      Path: /admin/
      Policies:
      - PolicyDocument:
          Statement:
            - Action:
                - '*'
              Effect: Allow
              Resource: '*'
            - Action: sts:AssumeRole
              Effect: Allow
              Resource: arn:aws:iam::*:role/admin
        PolicyName: AdminPolicy
    Type: AWS::IAM::Group
  AccountListing:
    Properties:
      GroupName: ListAccounts
      Path: /admin/
      Policies:
      - PolicyDocument:
          Statement:
            - Action:
                - 'organizations:ListAccounts'
              Effect: Allow
              Resource: '*'
        PolicyName: AccountListing
    Type: AWS::IAM::Group
