{% set Roles = ['Admin', 'Developer', 'CloudFormationDeveloper', 'ReadOnly', 'SecurityAudit', 'Operations'] %}

Resources:
  AssumeAccessAdministration:
    Type: AWS::IAM::Group
    Properties:
      GroupName: AssumeAccessAdministration
      Path: /admin/assume-access/
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - iam:AddUserToGroup
                Effect: Allow
                Resource:
                  {% for Role in Roles %}
                  - !Sub arn:aws:iam::${AWS::AccountId}:group/assume/{{Role | lower}}/Group*/Assume{{Role}}Group*
                  {% endfor %}
          PolicyName: Policy

  {% for Account in AWSSubAccounts%}
  {% for Role in Roles %}
  {{Role}}Group{{Account['Id']}}:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Assume{{Role}}Group{{Account['Id']}}
      Path: /assume/{{Role | lower}}/{{Account['Id']}}/
      Policies:
      - PolicyDocument:
          Statement:
            - Action:
                - sts:AssumeRole
              Effect: Allow
              Resource:
                - arn:aws:iam::{{Account['Id']}}:role/Assumable{{Role}}Role
        PolicyName: {{Role}}Policy{{Account['Id']}}
  {% endfor %}
  {% endfor %}
