Resources:
  GuardDutyDetector:
    Type: "AWS::GuardDuty::Detector"
    Properties:
      Enable: true

  {% for Account in Accounts %}
  GuardDutyMember{{Account['Id']}}:
    Type: "AWS::GuardDuty::Member"
    Properties:
      Status: "Invited"
      MemberId: "{{Account['Id']}}"
      Email: "{{Account['Email']}}"
      Message: "You are invited to enable Amazon Guardduty."
      DetectorId: !Ref GuardDutyDetector
      DisableEmailNotification: true
  {% endfor %}