stack-set: config-rules
all-subaccounts: true
all-regions: true
main-account-parameter: true
max-concurrent-percentage: 100
organization-variables: true
vars:
  EnabledRegions:
    - eu-central-1
    - us-east-1
capabilities:
  - CAPABILITY_IAM
