stack: password-policy
stack-set: password-policy
all-accounts: true
max-concurrent-percentage: 100
regions:
  - us-east-1
capabilities:
  - CAPABILITY_IAM
tags:
  ValidateAllAccounts: true
  ValidateRegions: us-east-1