{% from 'alerting.template.yaml' import AlertLevels%}
Parameters:
  SlackWebHookUrl:
    Type: String
    Default: ''

Conditions:
  HasSlackChannel: !Not [!Equals [!Ref SlackWebHookUrl, '']]

Resources:
  SlackNotifications:
    From: Modules::Lambda
    Properties:
      Code: |
        {{ code('slack_notifications.py') }}
      Environment:
        SLACK_WEBHOOK_URL: !Ref SlackWebHookUrl
      Timeout: 30

  {% for Level in AlertLevels %}
  SlackSubscription{{Level}}Topic:
    Condition: HasSlackChannel
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: !GetAtt SlackNotificationsLambdaFunction.Arn
      Protocol: "lambda"
      TopicArn: !Ref {{Level}}Topic

  SlackNotification{{Level}}LambdaPermission:
    Condition: HasSlackChannel
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt SlackNotificationsLambdaFunction.Arn
      Principal: sns.amazonaws.com
      SourceArn: !Ref {{Level}}Topic
    Type: AWS::Lambda::Permission
  {% endfor %}
